export enum HearingRole {
    APPELLANT = 'Appellant',
    DEFENCE_ADVOCATE = 'Defence Advocate',
    EXPERT = 'Expert',
    INTERPRETER = 'Interpreter',
    JUDGE = 'Judge',
    MACKENZIE_FRIEND = 'MacKenzie friend',
    OBSERVER = 'Observer',
    PANEL_MEMBER = 'Panel Member',
    PROSECUTION = 'Prosecution',
    PROSECUTION_ADVOCATE = 'Prosecution Advocate',
    REPRESENTATIVE = 'Representative',
    WINGER = 'Winger',
    WITNESS = 'Witness',
    LITIGANT_IN_PERSON = 'Litigant in person',
    STAFF_MEMBER = 'Staff Member',
    QUICK_LINK_PARTICIPANT = 'Quick link participant',
    QUICK_LINK_OBSERVER = 'Quick link observer',
}
