name: $(Date:yyyyMMddHHmm)-$(Rev:r)

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: master
      endpoint: hmcts

pool:
  vmImage: ubuntu-22.04

pr: none
trigger: none

variables:
  - group: vh-github-app-credentials

parameters:
  - name: prNumber
    displayName: Pull Request Number
    type: string

stages:
  - stage: uninstall_dev
    displayName: Uninstall Dev Helm and DNS
    dependsOn: []
    variables:
      - template: variables/dev.yaml
      - template: variables/shared.yaml
        parameters:
          env: ${{ variables.env }}
          prNumber: ${{ parameters.prNumber }}
      - name: dnsRecordName
        value: vh-${{ variables.git_repo_name }}-${{ variables.prTagPrefix }}
      - group: vh-tenant-creds
    jobs:
      - job: helm_uninstall
        displayName: Uninstall Helm from Dev
        steps:
          - template: templates\Azure\Aks\get-active-cluster.yaml@azTemplates
            parameters:
              subscriptionName: "${{ variables.subscriptionName }}"
              environment: ${{ variables.env }}

          - bash: |
              echo "$(appName)"

          - template: templates/Containerisation/helm/helm-uninstall.yaml@azTemplates
            parameters:
              namespace: "vh"
              releaseName: "${{ variables.chartName }}-${{ variables.prTagPrefix }}"
              azureSubscription: "${{ variables.subscriptionName }}"
              aksResourceGroupName: "$(aksCluster.resourceGroup)"
              aksClusterName: "$(aksCluster.name)"
      - job: dns_uninstall
        displayName: Uninstall DNS from Dev
        steps:
          - template: templates\Azure\Dns\private-dns-remove.yaml@azTemplates
            parameters:
              subscriptionName: "${{ variables.subscriptionName }}"
              dnsSubscriptionName: "${{ variables.dnsZoneSubscription }}"
              dnsResourceGroupName: "${{ variables.dnsZoneResourceGroup }}"
              zoneName: ${{ variables.dnsZone }}
              recordName: ${{ variables.dnsRecordName }}

      - job: redirect_url_remove
        displayName: Remove AAD Redirect Url
        steps:
          - template: templates\Azure\AAD\apps\add-remove-replyruls--no-sc.yaml@azTemplates
            parameters:
              azureClientId: $(vh_client_id)
              azureClientSecret: $(vh_client_secret)
              azureTenant: $(vh_tenant_id)
              action: "remove"
              domain: "https://${{ variables.dnsRecordName }}.${{ variables.dnsZone }}"
              name: "a${{ variables.gitRepoName }}.${{ variables.dnsZone }}"
              domainUris: ${{ variables.app_redirect_uri }}
              
