version: '3.4'

networks:
  integration-tests:
    driver: bridge

services:

  vh-video-web-tests:
    image: video-web-tests
    build:
      context: ./
      dockerfile: tests/Dockerfile
    entrypoint: /run-tests.sh
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SONAR_PROJECT_KEY=${SONAR_PROJECT_KEY}
      - SONAR_TOKEN=${SONAR_TOKEN}
      - SONAR_HOST=${SONAR_HOST}
      - SONAR_PROJECT_VERSION=${SONAR_PROJECT_VERSION}
      - SONAR_PROJECT_NAME=${SONAR_PROJECT_NAME}
      - SONAR_PR_KEY=${SONAR_PR_KEY}
      - SONAR_PR_BRANCH=${SONAR_PR_BRANCH}
      - SONAR_PR_BASE=${SONAR_PR_BASE}
    volumes:
      - ./TestResults:/TestResults:rw
      - ./Coverage:/Coverage:rw
      - ./:/app:rw
    networks:
      - integration-tests
