version: '3.4'

services:
  videoweb:
    image: ${DOCKER_REGISTRY-}videoweb
    build:
      context: .
      dockerfile: ./VideoWeb/VideoWeb/Dockerfile
      args:
        - skip_client_build=false
