import {
    ConferenceStatus,
    EndpointStatus,
    InterpreterType,
    LinkType,
    ParticipantStatus,
    Role,
    Supplier,
    TestScore
} from 'src/app/services/clients/api-client';
import { TransferDirection } from 'src/app/services/models/hearing-transfer';

export interface VHConference {
    id: string;
    scheduledDateTime: Date;
    endDateTime?: Date;
    duration: number;
    caseNumber: string;
    caseName: string;
    caseType: string;
    status: ConferenceStatus;
    hearingVenueName: string;
    isVenueScottish: boolean;
    participants: Array<VHParticipant>;
    endpoints: Array<VHEndpoint>;
    supplier: Supplier;
    countdownComplete?: boolean;
    audioRecordingIngestUrl: string;
    audioRecordingRequired: boolean;
    pexipNodeUri: string;
    selfTestNodeUri: string;
    conferenceAlias: string;
}

export interface VHParticipant {
    id: string;
    name: string;
    firstName: string;
    lastName: string;
    username: string;
    status: ParticipantStatus;
    displayName: string;
    tiledDisplayName: string;
    role: Role;
    hearingRole: string;
    representee?: string;
    pexipInfo?: VHPexipParticipant;
    room?: VHRoom;
    interpreterLanguage?: VHInterpreterLanguage;
    currentAudioMix?: string;
    linkedParticipants: Array<VHLinkedParticipant>;
    externalReferenceId?: string;
    protectedFrom?: string[];
    localMediaStatus?: LocalDeviceStatus;
    transferDirection?: TransferDirection;
}

export interface LocalDeviceStatus {
    isCameraOff: boolean;
    isMicrophoneMuted: boolean;
}

export interface VHEndpoint {
    id?: string;
    displayName: string | undefined;
    status: EndpointStatus;
    participantsLinked: string[] | undefined;
    room: VHRoom;
    pexipInfo?: VHPexipParticipant;
    interpreterLanguage?: VHInterpreterLanguage;
    externalReferenceId?: string;
    protectedFrom?: string[];
    transferDirection?: TransferDirection;
}

export interface VHPexipParticipant {
    /** Has been muted by a host */
    isRemoteMuted: boolean;
    /** Has been spotlighed by a host */
    isSpotlighted: boolean;
    /** Has muted their own video */
    isVideoMuted: boolean;
    /** Is hand raised */
    handRaised: boolean;
    /** The semi-colon delimited string provided to Pexip */
    pexipDisplayName: string;
    /** The unique ID generated by Pexip on connect */
    uuid: string;
    /** The optional call tag to identify a participant */
    callTag: string;
    /** Has the participant connected with audio only capabilties */
    isAudioOnlyCall: boolean;
    /** Has the participant connected with video capabilities */
    isVideoCall: boolean;
    /** The call protocol */
    protocol: string;
    /** The audio mix the participant is receiving audio from */
    receivingAudioMix: string;
    /** The audio mixes the participant is sending audio to */
    sentAudioMixes: Array<PexipAudioMix>;
    /** The level of privileges the participant has in the conference */
    role: string;
}

export interface VHPexipConference {
    guestsMuted: boolean;
    locked: boolean;
    started: boolean;
}

export interface VHRoom {
    label: string;
    locked: boolean;
}

export interface VHLinkedParticipant {
    linkedId?: string;
    linkedType?: LinkType;
}

export interface VHInterpreterLanguage {
    code: string;
    description: string;
    type: InterpreterType;
}

export interface VHConsultationCallStatus {
    participantId: string;
    callStatus: string;
    invitationId: string;
    roomLabel: string;
    requestedBy: string;
    requestedFor: string;
}

export interface VHParticipantMediaStatus {
    isLocalAudioMuted: boolean;
    isLocalVideoMuted: boolean;
}

export interface SelfTestScore {
    score?: TestScore;
    passed?: boolean;
}

export interface AudioRecordingState {
    continueWithoutRecording: boolean;
    recordingPaused: boolean;
    restartInProgress: boolean;
    wowzaConnectedAsAudioOnly: boolean;
    restartNotificationDisplayed: boolean;
}
