//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("1.6.1.0")]
[assembly: AssemblyVersion("1.6.1.0")]
[assembly: AssemblyInformationalVersion("1.6.1-VIH-5629-Add-version-property-to-healthcheck-endpoint-or-new-endpoint.1+181.Branch.feature-VIH-5629-Add-version-property-to-healthcheck-endpoint-or-new-endpoint.Sha.916ee537e129677e61ca9a8f9e4605fd4aa4cb6d")]